# Generated by Django 5.0 on 2024-05-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
